// Sample Data from design docs (ch4.md)

// TypeA: Base/foundational entities
const typeAData = [
    { id: 'app', title: 'app', description: '' },
    { id: 'app-near', title: 'app-near', description: '' },
    { id: 'application', title: 'application', description: '' },
    { id: 'audio-designer', title: 'audio-designer', description: '' },
    { id: 'blog', title: 'blog', description: '' },
    { id: 'blog-posts', title: 'blog-posts', description: '' },
    { id: 'book', title: 'book', description: '' },
    { id: 'club', title: 'club', description: '' },
    { id: 'competitors', title: 'competitors', description: '' },
    { id: 'conf', title: 'conf', description: '' },
    { id: 'cost', title: 'cost', description: '' },
    { id: 'course', title: 'course', description: '' },
    { id: 'course-near', title: 'course-near', description: '' },
    { id: 'crowd-funding', title: 'crowd-funding', description: '' },
    { id: 'customer-development', title: 'customer-development', description: '' },
    { id: 'demography', title: 'demography', description: '' },
    { id: 'deployment-cost', title: 'deployment-cost', description: '' },
    { id: 'design-docs', title: 'design-docs', description: '' },
    { id: 'development-cost', title: 'development-cost', description: '' },
    { id: 'ec-ga', title: 'ec-ga', description: '' },
    { id: 'editor', title: 'editor', description: '' },
    { id: 'edu', title: 'edu', description: '' },
    { id: 'environment', title: 'environment', description: '' },
    { id: 'event-exp', title: 'event-exp', description: '' },
    { id: 'freelance', title: 'freelance', description: '' },
    { id: 'game', title: 'game', description: '' },
    { id: 'game-designer', title: 'game-designer', description: '' },
    { id: 'game-near', title: 'game-near', description: '' },
    { id: 'goal', title: 'goal', description: '' },
    { id: 'government-investment', title: 'government-investment', description: '' },
    { id: 'homebrew', title: 'homebrew', description: '' },
    { id: 'industry-value', title: 'industry-value', description: '' },
    { id: 'input', title: 'input', description: '' },
    { id: 'input-model', title: 'input-model', description: '' },
    { id: 'input-valuable', title: 'input-valuable', description: '' },
    { id: 'internal-web', title: 'internal-web', description: '' },
    { id: 'investor', title: 'investor', description: '' },
    { id: 'investors', title: 'investors', description: '' },
    { id: 'market-size', title: 'market-size', description: '' },
    { id: 'marketing-specialist', title: 'marketing-specialist', description: '' },
    { id: 'n8n-app', title: 'n8n-app', description: '' },
    { id: 'office-workflow', title: 'office-workflow', description: '' },
    { id: 'output', title: 'output', description: '' },
    { id: 'output-valuable', title: 'output-valuable', description: '' },
    { id: 'people', title: 'people', description: '' },
    { id: 'people-near', title: 'people-near', description: '' },
    { id: 'pkm', title: 'pkm', description: '' },
    { id: 'podcast', title: 'podcast', description: '' },
    { id: 'producer', title: 'producer', description: '' },
    { id: 'products', title: 'products', description: '' },
    { id: 'programmer', title: 'programmer', description: '' },
    { id: 'prototype', title: 'prototype', description: '' },
    { id: 'public-speak', title: 'public-speak', description: '' },
    { id: 'publish-cost', title: 'publish-cost', description: '' },
    { id: 'published-app', title: 'published-app', description: '' },
    { id: 'published-articles', title: 'published-articles', description: '' },
    { id: 'published-book', title: 'published-book', description: '' },
    { id: 'published-course', title: 'published-course', description: '' },
    { id: 'published-game', title: 'published-game', description: '' },
    { id: 'published-videos', title: 'published-videos', description: '' },
    { id: 'publisher', title: 'publisher', description: '' },
    { id: 'revenue', title: 'revenue', description: '' },
    { id: 'rpa-app', title: 'rpa-app', description: '' },
    { id: 'skill-roadmap-coverage', title: 'skill-roadmap-coverage', description: '' },
    { id: 'students', title: 'students', description: '' },
    { id: 'studio', title: 'studio', description: '' },
    { id: 'studio-near', title: 'studio-near', description: '' },
    { id: 'tool', title: 'tool', description: '' },
    { id: 'tool-near', title: 'tool-near', description: '' },
    { id: 'tutor', title: 'tutor', description: '' },
    { id: 'uncat', title: 'uncat', description: '' },
    { id: 'users', title: 'users', description: '' },
    { id: 'visual-designer', title: 'visual-designer', description: '' },
    { id: 'web-scraper', title: 'web-scraper', description: '' },
    { id: 'website', title: 'website', description: '' },
    { id: 'YT-channel', title: 'YT-channel', description: '' }
];

// TypeB: Category buckets
const typeBData = [
    { id: 'game', title: 'game', description: '' },
    { id: 'edu', title: 'edu', description: '' },
    { id: 'pkm', title: 'pkm', description: '' },
    { id: 'freelance', title: 'freelance', description: '' }
];

// TypeB1: Hierarchical tree structure (instances of TypeA within TypeB)
// Structure: { typeBId: { nodeId: { typeAId, parentId, children: [] } } }
const typeB1Data = {
    game: {
        root: { id: 'root', typeAId: 'game', parentId: null, children: ['input', 'input-model', 'input-valuable', 'output', 'output-valuable', 'goal', 'environment', 'uncat'] },
        input: { id: 'input', typeAId: 'input', parentId: 'root', children: ['input-book', 'input-conf', 'input-club', 'input-blog', 'input-website', 'input-podcast', 'input-yt'] },
        'input-book': { id: 'input-book', typeAId: 'book', parentId: 'input', children: [] },
        'input-conf': { id: 'input-conf', typeAId: 'conf', parentId: 'input', children: [] },
        'input-club': { id: 'input-club', typeAId: 'club', parentId: 'input', children: [] },
        'input-blog': { id: 'input-blog', typeAId: 'blog', parentId: 'input', children: [] },
        'input-website': { id: 'input-website', typeAId: 'website', parentId: 'input', children: [] },
        'input-podcast': { id: 'input-podcast', typeAId: 'podcast', parentId: 'input', children: [] },
        'input-yt': { id: 'input-yt', typeAId: 'YT-channel', parentId: 'input', children: [] },
        'input-model': { id: 'input-model', typeAId: 'input-model', parentId: 'root', children: ['im-people-near', 'im-people', 'im-studio-near', 'im-studio', 'im-game-near', 'im-game'] },
        'im-people-near': { id: 'im-people-near', typeAId: 'people-near', parentId: 'input-model', children: [] },
        'im-people': { id: 'im-people', typeAId: 'people', parentId: 'input-model', children: [] },
        'im-studio-near': { id: 'im-studio-near', typeAId: 'studio-near', parentId: 'input-model', children: [] },
        'im-studio': { id: 'im-studio', typeAId: 'studio', parentId: 'input-model', children: [] },
        'im-game-near': { id: 'im-game-near', typeAId: 'game-near', parentId: 'input-model', children: [] },
        'im-game': { id: 'im-game', typeAId: 'game', parentId: 'input-model', children: [] },
        'input-valuable': { id: 'input-valuable', typeAId: 'input-valuable', parentId: 'root', children: ['iv-visual', 'iv-programmer', 'iv-publisher', 'iv-audio', 'iv-game-designer', 'iv-investor'] },
        'iv-visual': { id: 'iv-visual', typeAId: 'visual-designer', parentId: 'input-valuable', children: [] },
        'iv-programmer': { id: 'iv-programmer', typeAId: 'programmer', parentId: 'input-valuable', children: [] },
        'iv-publisher': { id: 'iv-publisher', typeAId: 'publisher', parentId: 'input-valuable', children: [] },
        'iv-audio': { id: 'iv-audio', typeAId: 'audio-designer', parentId: 'input-valuable', children: [] },
        'iv-game-designer': { id: 'iv-game-designer', typeAId: 'game-designer', parentId: 'input-valuable', children: [] },
        'iv-investor': { id: 'iv-investor', typeAId: 'investor', parentId: 'input-valuable', children: [] },
        output: { id: 'output', typeAId: 'output', parentId: 'root', children: ['out-event', 'out-design', 'out-prototype', 'out-website', 'out-blog'] },
        'out-event': { id: 'out-event', typeAId: 'event-exp', parentId: 'output', children: [] },
        'out-design': { id: 'out-design', typeAId: 'design-docs', parentId: 'output', children: [] },
        'out-prototype': { id: 'out-prototype', typeAId: 'prototype', parentId: 'output', children: [] },
        'out-website': { id: 'out-website', typeAId: 'website', parentId: 'output', children: [] },
        'out-blog': { id: 'out-blog', typeAId: 'blog-posts', parentId: 'output', children: [] },
        'output-valuable': { id: 'output-valuable', typeAId: 'output-valuable', parentId: 'root', children: ['ov-game', 'ov-articles', 'ov-book', 'ov-speak'] },
        'ov-game': { id: 'ov-game', typeAId: 'published-game', parentId: 'output-valuable', children: [] },
        'ov-articles': { id: 'ov-articles', typeAId: 'published-articles', parentId: 'output-valuable', children: [] },
        'ov-book': { id: 'ov-book', typeAId: 'published-book', parentId: 'output-valuable', children: [] },
        'ov-speak': { id: 'ov-speak', typeAId: 'public-speak', parentId: 'output-valuable', children: [] },
        goal: { id: 'goal', typeAId: 'goal', parentId: 'root', children: ['goal-revenue', 'goal-iv', 'goal-ov', 'goal-skill'] },
        'goal-revenue': { id: 'goal-revenue', typeAId: 'revenue', parentId: 'goal', children: [] },
        'goal-iv': { id: 'goal-iv', typeAId: 'input-valuable', parentId: 'goal', children: [] },
        'goal-ov': { id: 'goal-ov', typeAId: 'output-valuable', parentId: 'goal', children: [] },
        'goal-skill': { id: 'goal-skill', typeAId: 'skill-roadmap-coverage', parentId: 'goal', children: [] },
        environment: { id: 'environment', typeAId: 'environment', parentId: 'root', children: ['env-market', 'env-competitors', 'env-cost', 'env-investors'] },
        'env-market': { id: 'env-market', typeAId: 'market-size', parentId: 'environment', children: ['market-industry', 'market-demo'] },
        'market-industry': { id: 'market-industry', typeAId: 'industry-value', parentId: 'env-market', children: [] },
        'market-demo': { id: 'market-demo', typeAId: 'demography', parentId: 'env-market', children: [] },
        'env-competitors': { id: 'env-competitors', typeAId: 'competitors', parentId: 'environment', children: ['comp-demo', 'comp-products'] },
        'comp-demo': { id: 'comp-demo', typeAId: 'demography', parentId: 'env-competitors', children: [] },
        'comp-products': { id: 'comp-products', typeAId: 'products', parentId: 'env-competitors', children: [] },
        'env-cost': { id: 'env-cost', typeAId: 'cost', parentId: 'environment', children: ['cost-dev', 'cost-deploy', 'cost-publish'] },
        'cost-dev': { id: 'cost-dev', typeAId: 'development-cost', parentId: 'env-cost', children: [] },
        'cost-deploy': { id: 'cost-deploy', typeAId: 'deployment-cost', parentId: 'env-cost', children: [] },
        'cost-publish': { id: 'cost-publish', typeAId: 'publish-cost', parentId: 'env-cost', children: [] },
        'env-investors': { id: 'env-investors', typeAId: 'investors', parentId: 'environment', children: ['inv-gov', 'inv-crowd'] },
        'inv-gov': { id: 'inv-gov', typeAId: 'government-investment', parentId: 'env-investors', children: [] },
        'inv-crowd': { id: 'inv-crowd', typeAId: 'crowd-funding', parentId: 'env-investors', children: [] },
        uncat: { id: 'uncat', typeAId: 'uncat', parentId: 'root', children: [] }
    },
    edu: {
        root: { id: 'root', typeAId: 'edu', parentId: null, children: ['input', 'input-model', 'input-valuable', 'output', 'output-valuable', 'goal', 'environment', 'uncat'] },
        input: { id: 'input', typeAId: 'input', parentId: 'root', children: ['input-book', 'input-conf', 'input-club', 'input-blog', 'input-website', 'input-podcast', 'input-yt'] },
        'input-book': { id: 'input-book', typeAId: 'book', parentId: 'input', children: [] },
        'input-conf': { id: 'input-conf', typeAId: 'conf', parentId: 'input', children: [] },
        'input-club': { id: 'input-club', typeAId: 'club', parentId: 'input', children: [] },
        'input-blog': { id: 'input-blog', typeAId: 'blog', parentId: 'input', children: [] },
        'input-website': { id: 'input-website', typeAId: 'website', parentId: 'input', children: [] },
        'input-podcast': { id: 'input-podcast', typeAId: 'podcast', parentId: 'input', children: [] },
        'input-yt': { id: 'input-yt', typeAId: 'YT-channel', parentId: 'input', children: [] },
        'input-model': { id: 'input-model', typeAId: 'input-model', parentId: 'root', children: ['im-people-near', 'im-people', 'im-studio-near', 'im-studio', 'im-course-near', 'im-course'] },
        'im-people-near': { id: 'im-people-near', typeAId: 'people-near', parentId: 'input-model', children: [] },
        'im-people': { id: 'im-people', typeAId: 'people', parentId: 'input-model', children: [] },
        'im-studio-near': { id: 'im-studio-near', typeAId: 'studio-near', parentId: 'input-model', children: [] },
        'im-studio': { id: 'im-studio', typeAId: 'studio', parentId: 'input-model', children: [] },
        'im-course-near': { id: 'im-course-near', typeAId: 'course-near', parentId: 'input-model', children: [] },
        'im-course': { id: 'im-course', typeAId: 'course', parentId: 'input-model', children: [] },
        'input-valuable': { id: 'input-valuable', typeAId: 'input-valuable', parentId: 'root', children: ['iv-visual', 'iv-marketing', 'iv-publisher', 'iv-producer', 'iv-editor', 'iv-investor'] },
        'iv-visual': { id: 'iv-visual', typeAId: 'visual-designer', parentId: 'input-valuable', children: [] },
        'iv-marketing': { id: 'iv-marketing', typeAId: 'marketing-specialist', parentId: 'input-valuable', children: [] },
        'iv-publisher': { id: 'iv-publisher', typeAId: 'publisher', parentId: 'input-valuable', children: [] },
        'iv-producer': { id: 'iv-producer', typeAId: 'producer', parentId: 'input-valuable', children: [] },
        'iv-editor': { id: 'iv-editor', typeAId: 'editor', parentId: 'input-valuable', children: [] },
        'iv-investor': { id: 'iv-investor', typeAId: 'investor', parentId: 'input-valuable', children: [] },
        output: { id: 'output', typeAId: 'output', parentId: 'root', children: ['out-event', 'out-blog', 'out-tutor'] },
        'out-event': { id: 'out-event', typeAId: 'event-exp', parentId: 'output', children: [] },
        'out-blog': { id: 'out-blog', typeAId: 'blog-posts', parentId: 'output', children: [] },
        'out-tutor': { id: 'out-tutor', typeAId: 'tutor', parentId: 'output', children: [] },
        'output-valuable': { id: 'output-valuable', typeAId: 'output-valuable', parentId: 'root', children: ['ov-course', 'ov-articles', 'ov-videos', 'ov-book', 'ov-speak'] },
        'ov-course': { id: 'ov-course', typeAId: 'published-course', parentId: 'output-valuable', children: [] },
        'ov-articles': { id: 'ov-articles', typeAId: 'published-articles', parentId: 'output-valuable', children: [] },
        'ov-videos': { id: 'ov-videos', typeAId: 'published-videos', parentId: 'output-valuable', children: [] },
        'ov-book': { id: 'ov-book', typeAId: 'published-book', parentId: 'output-valuable', children: [] },
        'ov-speak': { id: 'ov-speak', typeAId: 'public-speak', parentId: 'output-valuable', children: [] },
        goal: { id: 'goal', typeAId: 'goal', parentId: 'root', children: ['goal-revenue', 'goal-iv', 'goal-ov', 'goal-skill'] },
        'goal-revenue': { id: 'goal-revenue', typeAId: 'revenue', parentId: 'goal', children: [] },
        'goal-iv': { id: 'goal-iv', typeAId: 'input-valuable', parentId: 'goal', children: [] },
        'goal-ov': { id: 'goal-ov', typeAId: 'output-valuable', parentId: 'goal', children: [] },
        'goal-skill': { id: 'goal-skill', typeAId: 'skill-roadmap-coverage', parentId: 'goal', children: [] },
        environment: { id: 'environment', typeAId: 'environment', parentId: 'root', children: ['env-market', 'env-competitors', 'env-cost', 'env-investors'] },
        'env-market': { id: 'env-market', typeAId: 'market-size', parentId: 'environment', children: ['market-industry', 'market-demo'] },
        'market-industry': { id: 'market-industry', typeAId: 'industry-value', parentId: 'env-market', children: [] },
        'market-demo': { id: 'market-demo', typeAId: 'demography', parentId: 'env-market', children: [] },
        'env-competitors': { id: 'env-competitors', typeAId: 'competitors', parentId: 'environment', children: ['comp-demo', 'comp-products'] },
        'comp-demo': { id: 'comp-demo', typeAId: 'demography', parentId: 'env-competitors', children: [] },
        'comp-products': { id: 'comp-products', typeAId: 'products', parentId: 'env-competitors', children: [] },
        'env-cost': { id: 'env-cost', typeAId: 'cost', parentId: 'environment', children: ['cost-dev', 'cost-publish'] },
        'cost-dev': { id: 'cost-dev', typeAId: 'development-cost', parentId: 'env-cost', children: [] },
        'cost-publish': { id: 'cost-publish', typeAId: 'publish-cost', parentId: 'env-cost', children: [] },
        'env-investors': { id: 'env-investors', typeAId: 'investors', parentId: 'environment', children: ['inv-gov'] },
        'inv-gov': { id: 'inv-gov', typeAId: 'government-investment', parentId: 'env-investors', children: [] },
        uncat: { id: 'uncat', typeAId: 'uncat', parentId: 'root', children: [] }
    },
    pkm: {
        root: { id: 'root', typeAId: 'pkm', parentId: null, children: ['input', 'input-model', 'input-valuable', 'output', 'output-valuable', 'goal', 'environment', 'uncat'] },
        input: { id: 'input', typeAId: 'input', parentId: 'root', children: ['input-book', 'input-conf', 'input-club', 'input-blog', 'input-website', 'input-podcast', 'input-yt'] },
        'input-book': { id: 'input-book', typeAId: 'book', parentId: 'input', children: [] },
        'input-conf': { id: 'input-conf', typeAId: 'conf', parentId: 'input', children: [] },
        'input-club': { id: 'input-club', typeAId: 'club', parentId: 'input', children: [] },
        'input-blog': { id: 'input-blog', typeAId: 'blog', parentId: 'input', children: [] },
        'input-website': { id: 'input-website', typeAId: 'website', parentId: 'input', children: [] },
        'input-podcast': { id: 'input-podcast', typeAId: 'podcast', parentId: 'input', children: [] },
        'input-yt': { id: 'input-yt', typeAId: 'YT-channel', parentId: 'input', children: [] },
        'input-model': { id: 'input-model', typeAId: 'input-model', parentId: 'root', children: ['im-people-near', 'im-people', 'im-studio-near', 'im-studio', 'im-app-near', 'im-app', 'im-course-near', 'im-course'] },
        'im-people-near': { id: 'im-people-near', typeAId: 'people-near', parentId: 'input-model', children: [] },
        'im-people': { id: 'im-people', typeAId: 'people', parentId: 'input-model', children: [] },
        'im-studio-near': { id: 'im-studio-near', typeAId: 'studio-near', parentId: 'input-model', children: [] },
        'im-studio': { id: 'im-studio', typeAId: 'studio', parentId: 'input-model', children: [] },
        'im-app-near': { id: 'im-app-near', typeAId: 'app-near', parentId: 'input-model', children: [] },
        'im-app': { id: 'im-app', typeAId: 'app', parentId: 'input-model', children: [] },
        'im-course-near': { id: 'im-course-near', typeAId: 'course-near', parentId: 'input-model', children: [] },
        'im-course': { id: 'im-course', typeAId: 'course', parentId: 'input-model', children: [] },
        'input-valuable': { id: 'input-valuable', typeAId: 'input-valuable', parentId: 'root', children: ['iv-visual', 'iv-programmer', 'iv-publisher', 'iv-investor'] },
        'iv-visual': { id: 'iv-visual', typeAId: 'visual-designer', parentId: 'input-valuable', children: [] },
        'iv-programmer': { id: 'iv-programmer', typeAId: 'programmer', parentId: 'input-valuable', children: [] },
        'iv-publisher': { id: 'iv-publisher', typeAId: 'publisher', parentId: 'input-valuable', children: [] },
        'iv-investor': { id: 'iv-investor', typeAId: 'investor', parentId: 'input-valuable', children: [] },
        output: { id: 'output', typeAId: 'output', parentId: 'root', children: ['out-design', 'out-course', 'out-prototype', 'out-event', 'out-blog'] },
        'out-design': { id: 'out-design', typeAId: 'design-docs', parentId: 'output', children: [] },
        'out-course': { id: 'out-course', typeAId: 'course', parentId: 'output', children: [] },
        'out-prototype': { id: 'out-prototype', typeAId: 'prototype', parentId: 'output', children: [] },
        'out-event': { id: 'out-event', typeAId: 'event-exp', parentId: 'output', children: [] },
        'out-blog': { id: 'out-blog', typeAId: 'blog-posts', parentId: 'output', children: [] },
        'output-valuable': { id: 'output-valuable', typeAId: 'output-valuable', parentId: 'root', children: ['ov-app', 'ov-articles', 'ov-book', 'ov-speak'] },
        'ov-app': { id: 'ov-app', typeAId: 'published-app', parentId: 'output-valuable', children: [] },
        'ov-articles': { id: 'ov-articles', typeAId: 'published-articles', parentId: 'output-valuable', children: [] },
        'ov-book': { id: 'ov-book', typeAId: 'published-book', parentId: 'output-valuable', children: [] },
        'ov-speak': { id: 'ov-speak', typeAId: 'public-speak', parentId: 'output-valuable', children: [] },
        goal: { id: 'goal', typeAId: 'goal', parentId: 'root', children: ['goal-revenue', 'goal-iv', 'goal-ov', 'goal-skill'] },
        'goal-revenue': { id: 'goal-revenue', typeAId: 'revenue', parentId: 'goal', children: [] },
        'goal-iv': { id: 'goal-iv', typeAId: 'input-valuable', parentId: 'goal', children: [] },
        'goal-ov': { id: 'goal-ov', typeAId: 'output-valuable', parentId: 'goal', children: [] },
        'goal-skill': { id: 'goal-skill', typeAId: 'skill-roadmap-coverage', parentId: 'goal', children: [] },
        environment: { id: 'environment', typeAId: 'environment', parentId: 'root', children: ['env-market', 'env-competitors', 'env-cost', 'env-investors'] },
        'env-market': { id: 'env-market', typeAId: 'market-size', parentId: 'environment', children: ['market-industry', 'market-demo'] },
        'market-industry': { id: 'market-industry', typeAId: 'industry-value', parentId: 'env-market', children: [] },
        'market-demo': { id: 'market-demo', typeAId: 'demography', parentId: 'env-market', children: [] },
        'env-competitors': { id: 'env-competitors', typeAId: 'competitors', parentId: 'environment', children: ['comp-demo', 'comp-products'] },
        'comp-demo': { id: 'comp-demo', typeAId: 'demography', parentId: 'env-competitors', children: [] },
        'comp-products': { id: 'comp-products', typeAId: 'products', parentId: 'env-competitors', children: [] },
        'env-cost': { id: 'env-cost', typeAId: 'cost', parentId: 'environment', children: ['cost-dev', 'cost-deploy', 'cost-publish'] },
        'cost-dev': { id: 'cost-dev', typeAId: 'development-cost', parentId: 'env-cost', children: [] },
        'cost-deploy': { id: 'cost-deploy', typeAId: 'deployment-cost', parentId: 'env-cost', children: [] },
        'cost-publish': { id: 'cost-publish', typeAId: 'publish-cost', parentId: 'env-cost', children: [] },
        'env-investors': { id: 'env-investors', typeAId: 'investors', parentId: 'environment', children: ['inv-gov', 'inv-crowd'] },
        'inv-gov': { id: 'inv-gov', typeAId: 'government-investment', parentId: 'env-investors', children: [] },
        'inv-crowd': { id: 'inv-crowd', typeAId: 'crowd-funding', parentId: 'env-investors', children: [] },
        uncat: { id: 'uncat', typeAId: 'uncat', parentId: 'root', children: [] }
    },
    freelance: {
        root: { id: 'root', typeAId: 'freelance', parentId: null, children: ['input', 'input-model', 'input-valuable', 'output', 'output-valuable', 'goal', 'environment', 'uncat'] },
        input: { id: 'input', typeAId: 'input', parentId: 'root', children: ['input-book', 'input-conf', 'input-club', 'input-blog', 'input-website', 'input-podcast', 'input-yt'] },
        'input-book': { id: 'input-book', typeAId: 'book', parentId: 'input', children: [] },
        'input-conf': { id: 'input-conf', typeAId: 'conf', parentId: 'input', children: [] },
        'input-club': { id: 'input-club', typeAId: 'club', parentId: 'input', children: [] },
        'input-blog': { id: 'input-blog', typeAId: 'blog', parentId: 'input', children: [] },
        'input-website': { id: 'input-website', typeAId: 'website', parentId: 'input', children: [] },
        'input-podcast': { id: 'input-podcast', typeAId: 'podcast', parentId: 'input', children: [] },
        'input-yt': { id: 'input-yt', typeAId: 'YT-channel', parentId: 'input', children: [] },
        'input-model': { id: 'input-model', typeAId: 'input-model', parentId: 'root', children: ['im-people-near', 'im-people', 'im-studio-near', 'im-studio', 'im-tool-near', 'im-tool'] },
        'im-people-near': { id: 'im-people-near', typeAId: 'people-near', parentId: 'input-model', children: [] },
        'im-people': { id: 'im-people', typeAId: 'people', parentId: 'input-model', children: [] },
        'im-studio-near': { id: 'im-studio-near', typeAId: 'studio-near', parentId: 'input-model', children: [] },
        'im-studio': { id: 'im-studio', typeAId: 'studio', parentId: 'input-model', children: [] },
        'im-tool-near': { id: 'im-tool-near', typeAId: 'tool-near', parentId: 'input-model', children: [] },
        'im-tool': { id: 'im-tool', typeAId: 'tool', parentId: 'input-model', children: [] },
        'input-valuable': { id: 'input-valuable', typeAId: 'input-valuable', parentId: 'root', children: ['iv-visual', 'iv-programmer', 'iv-users', 'iv-investor'] },
        'iv-visual': { id: 'iv-visual', typeAId: 'visual-designer', parentId: 'input-valuable', children: [] },
        'iv-programmer': { id: 'iv-programmer', typeAId: 'programmer', parentId: 'input-valuable', children: [] },
        'iv-users': { id: 'iv-users', typeAId: 'users', parentId: 'input-valuable', children: [] },
        'iv-investor': { id: 'iv-investor', typeAId: 'investor', parentId: 'input-valuable', children: [] },
        output: { id: 'output', typeAId: 'output', parentId: 'root', children: ['out-n8n', 'out-event', 'out-internal', 'out-website', 'out-ec', 'out-rpa', 'out-office', 'out-scraper'] },
        'out-n8n': { id: 'out-n8n', typeAId: 'n8n-app', parentId: 'output', children: [] },
        'out-event': { id: 'out-event', typeAId: 'event-exp', parentId: 'output', children: [] },
        'out-internal': { id: 'out-internal', typeAId: 'internal-web', parentId: 'output', children: [] },
        'out-website': { id: 'out-website', typeAId: 'website', parentId: 'output', children: [] },
        'out-ec': { id: 'out-ec', typeAId: 'ec-ga', parentId: 'output', children: [] },
        'out-rpa': { id: 'out-rpa', typeAId: 'rpa-app', parentId: 'output', children: [] },
        'out-office': { id: 'out-office', typeAId: 'office-workflow', parentId: 'output', children: [] },
        'out-scraper': { id: 'out-scraper', typeAId: 'web-scraper', parentId: 'output', children: [] },
        'output-valuable': { id: 'output-valuable', typeAId: 'output-valuable', parentId: 'root', children: ['ov-app', 'ov-articles', 'ov-book', 'ov-speak'] },
        'ov-app': { id: 'ov-app', typeAId: 'published-app', parentId: 'output-valuable', children: [] },
        'ov-articles': { id: 'ov-articles', typeAId: 'published-articles', parentId: 'output-valuable', children: [] },
        'ov-book': { id: 'ov-book', typeAId: 'published-book', parentId: 'output-valuable', children: [] },
        'ov-speak': { id: 'ov-speak', typeAId: 'public-speak', parentId: 'output-valuable', children: [] },
        goal: { id: 'goal', typeAId: 'goal', parentId: 'root', children: ['goal-revenue', 'goal-iv', 'goal-ov', 'goal-skill'] },
        'goal-revenue': { id: 'goal-revenue', typeAId: 'revenue', parentId: 'goal', children: [] },
        'goal-iv': { id: 'goal-iv', typeAId: 'input-valuable', parentId: 'goal', children: [] },
        'goal-ov': { id: 'goal-ov', typeAId: 'output-valuable', parentId: 'goal', children: [] },
        'goal-skill': { id: 'goal-skill', typeAId: 'skill-roadmap-coverage', parentId: 'goal', children: [] },
        environment: { id: 'environment', typeAId: 'environment', parentId: 'root', children: ['env-market', 'env-competitors', 'env-cost', 'env-investors'] },
        'env-market': { id: 'env-market', typeAId: 'market-size', parentId: 'environment', children: ['market-industry', 'market-demo'] },
        'market-industry': { id: 'market-industry', typeAId: 'industry-value', parentId: 'env-market', children: [] },
        'market-demo': { id: 'market-demo', typeAId: 'demography', parentId: 'env-market', children: [] },
        'env-competitors': { id: 'env-competitors', typeAId: 'competitors', parentId: 'environment', children: ['comp-demo', 'comp-products', 'comp-homebrew', 'comp-students'] },
        'comp-demo': { id: 'comp-demo', typeAId: 'demography', parentId: 'env-competitors', children: [] },
        'comp-products': { id: 'comp-products', typeAId: 'products', parentId: 'env-competitors', children: [] },
        'comp-homebrew': { id: 'comp-homebrew', typeAId: 'homebrew', parentId: 'env-competitors', children: [] },
        'comp-students': { id: 'comp-students', typeAId: 'students', parentId: 'env-competitors', children: [] },
        'env-cost': { id: 'env-cost', typeAId: 'cost', parentId: 'environment', children: ['cost-dev', 'cost-deploy', 'cost-customer'] },
        'cost-dev': { id: 'cost-dev', typeAId: 'development-cost', parentId: 'env-cost', children: [] },
        'cost-deploy': { id: 'cost-deploy', typeAId: 'deployment-cost', parentId: 'env-cost', children: [] },
        'cost-customer': { id: 'cost-customer', typeAId: 'customer-development', parentId: 'env-cost', children: [] },
        'env-investors': { id: 'env-investors', typeAId: 'investors', parentId: 'environment', children: ['inv-gov', 'inv-crowd'] },
        'inv-gov': { id: 'inv-gov', typeAId: 'government-investment', parentId: 'env-investors', children: [] },
        'inv-crowd': { id: 'inv-crowd', typeAId: 'crowd-funding', parentId: 'env-investors', children: [] },
        uncat: { id: 'uncat', typeAId: 'uncat', parentId: 'root', children: [] }
    }
};

// TypeB2: Relations between TypeB1 and TypeC
// Structure: { typeBId: { typeB1Id: [{ id, typeCId, color, char }] } }
const typeB2Data = {
    game: {
        'out-prototype': [
            { id: 'b2-game-1', typeCId: 'tc-vim-keys', color: '#8931EF', char: 'A' }
        ],
        'out-blog': [
            { id: 'b2-game-2', typeCId: 'tc-blog-writing', color: '#F2CA19', char: 'B' }
        ]
    },
    edu: {
        'out-event': [
            { id: 'b2-edu-1', typeCId: 'tc-langchain', color: '#FF00BD', char: 'C' }
        ],
        'out-blog': [
            { id: 'b2-edu-2', typeCId: 'tc-blog-writing', color: '#F2CA19', char: 'B' }
        ]
    },
    pkm: {
        'out-blog': [
            { id: 'b2-pkm-1', typeCId: 'tc-blog-writing', color: '#F2CA19', char: 'B' }
        ],
        'out-prototype': [
            { id: 'b2-pkm-2', typeCId: 'tc-word-count', color: '#0057E9', char: 'D' },
            { id: 'b2-pkm-3', typeCId: 'tc-kb-catalog', color: '#87E911', char: 'E' },
            { id: 'b2-pkm-4', typeCId: 'tc-mandala', color: '#E11845', char: 'F' },
            { id: 'b2-pkm-5', typeCId: 'tc-gantt', color: '#8931EF', char: 'G' }
        ]
    },
    freelance: {
        'input-club': [
            { id: 'b2-fl-1', typeCId: 'tc-bni', color: '#F2CA19', char: 'H' }
        ],
        'out-internal': [
            { id: 'b2-fl-2', typeCId: 'tc-pig-farm', color: '#FF00BD', char: 'I' },
            { id: 'b2-fl-3', typeCId: 'tc-cyber', color: '#0057E9', char: 'J' },
            { id: 'b2-fl-4', typeCId: 'tc-eip4', color: '#87E911', char: 'K' },
            { id: 'b2-fl-5', typeCId: 'tc-logistic', color: '#E11845', char: 'L' },
            { id: 'b2-fl-6', typeCId: 'tc-tsc-fit', color: '#8931EF', char: 'M' }
        ],
        'out-ec': [
            { id: 'b2-fl-7', typeCId: 'tc-ecpay', color: '#F2CA19', char: 'N' }
        ],
        'out-website': [
            { id: 'b2-fl-8', typeCId: 'tc-cms2', color: '#FF00BD', char: 'O' },
            { id: 'b2-fl-9', typeCId: 'tc-company-web', color: '#0057E9', char: 'P' },
            { id: 'b2-fl-10', typeCId: 'tc-blog-site', color: '#87E911', char: 'Q' }
        ],
        'out-rpa': [
            { id: 'b2-fl-11', typeCId: 'tc-rpa-blog', color: '#E11845', char: 'R' },
            { id: 'b2-fl-12', typeCId: 'tc-rpa-ezcard', color: '#8931EF', char: 'S' },
            { id: 'b2-fl-13', typeCId: 'tc-rpa-elearn', color: '#F2CA19', char: 'T' },
            { id: 'b2-fl-14', typeCId: 'tc-rpa-infinitode', color: '#FF00BD', char: 'U' },
            { id: 'b2-fl-15', typeCId: 'tc-rpa-order', color: '#0057E9', char: 'V' },
            { id: 'b2-fl-16', typeCId: 'tc-rpa-punch', color: '#87E911', char: 'W' },
            { id: 'b2-fl-17', typeCId: 'tc-rpa-sso', color: '#E11845', char: 'X' }
        ],
        'out-office': [
            { id: 'b2-fl-18', typeCId: 'tc-aws-wf', color: '#8931EF', char: 'Y' },
            { id: 'b2-fl-19', typeCId: 'tc-sales-wf', color: '#F2CA19', char: 'Z' },
            { id: 'b2-fl-20', typeCId: 'tc-rtf-2020', color: '#FF00BD', char: '0' },
            { id: 'b2-fl-21', typeCId: 'tc-rtf', color: '#0057E9', char: '1' },
            { id: 'b2-fl-22', typeCId: 'tc-vba-gantt', color: '#87E911', char: '2' },
            { id: 'b2-fl-23', typeCId: 'tc-vba-andy', color: '#E11845', char: '3' }
        ],
        'out-scraper': [
            { id: 'b2-fl-24', typeCId: 'tc-scraper-104', color: '#8931EF', char: '4' },
            { id: 'b2-fl-25', typeCId: 'tc-scraper-591', color: '#F2CA19', char: '5' },
            { id: 'b2-fl-26', typeCId: 'tc-scraper-movie', color: '#FF00BD', char: '6' }
        ]
    }
};

// TypeC: Concrete work products/deliverables
const typeCData = [
    { id: 'tc-eip4', title: 'I made web apps EIP 4.0', description: '' },
    { id: 'tc-cms2', title: 'I made web apps CMS 2.0', description: '' },
    { id: 'tc-tsc-fit', title: 'I made web apps TSC Fit', description: '' },
    { id: 'tc-logistic', title: 'I made web apps Logistic admin platform', description: '' },
    { id: 'tc-blog-site', title: 'I made web apps blog (next, astro, starlight, astro)', description: '' },
    { id: 'tc-vim-keys', title: 'I made video games VIM Keys Game', description: '' },
    { id: 'tc-cyber', title: 'I made service integration cyber security intl', description: '' },
    { id: 'tc-elk', title: 'I made backend stuff ELK', description: '' },
    { id: 'tc-autobot', title: 'I made backend stuff suspicious autobot report', description: '' },
    { id: 'tc-api-wrapper', title: 'I maintained backend stuff API Wrapper for native-app client', description: '' },
    { id: 'tc-statement', title: 'I maintained backend stuff Statement, Result, Onebook member', description: '' },
    { id: 'tc-postman', title: 'I maintained backend stuff postman integration test', description: '' },
    { id: 'tc-eform', title: 'I maintained web apps Eform', description: '' },
    { id: 'tc-myreport', title: 'I maintained web apps MyReport', description: '' },
    { id: 'tc-smart', title: 'I maintained web apps SMART', description: '' },
    { id: 'tc-vscode-ext', title: 'I made devops tools vscode md ext', description: '' },
    { id: 'tc-fit-admin', title: 'I made devops tools TSC Fit admin tool', description: '' },
    { id: 'tc-query-site', title: 'I made devops tools query site stuff', description: '' },
    { id: 'tc-signalr', title: 'I made devops tools config signalR', description: '' },
    { id: 'tc-um-update', title: 'I made devops tools UM services update automation', description: '' },
    { id: 'tc-vba-andy', title: 'I do office automation VBA Refactor Andy Hsieh', description: '' },
    { id: 'tc-vba-gantt', title: 'I do office automation VBA Gantt', description: '' },
    { id: 'tc-rtf', title: 'I do office automation RTF Transformer', description: '' },
    { id: 'tc-rtf-2020', title: 'I do office automation 2020 RTF parser rework', description: '' },
    { id: 'tc-rpa-blog', title: 'I made RPA apps Cross platform data transfer blog post', description: '' },
    { id: 'tc-rpa-ezcard', title: 'I made RPA apps Cross platform data transfer ezcard data', description: '' },
    { id: 'tc-rpa-punch', title: 'I made RPA apps Punch clock automation', description: '' },
    { id: 'tc-rpa-infinitode', title: 'I made RPA apps Infinitode Parser', description: '' },
    { id: 'tc-rpa-sso', title: 'I made RPA apps SSO AD EIP Account Sync', description: '' },
    { id: 'tc-rpa-elearn', title: 'I made RPA apps Elearning auto-click', description: '' },
    { id: 'tc-rpa-order', title: 'I made RPA apps One-shot ordering bot', description: '' },
    { id: 'tc-scraper-104', title: 'I made web scraper 104 Parser', description: '' },
    { id: 'tc-scraper-movie', title: 'I made web scraper Movie Parser', description: '' },
    { id: 'tc-scraper-591', title: 'I made web scraper 591 Parser', description: '' },
    { id: 'tc-pig-farm', title: 'I freelance pig farm eform', description: '' },
    { id: 'tc-company-web', title: 'I freelance company-website logo biz-card', description: '' },
    { id: 'tc-ecpay', title: 'I freelance ecpay module upgrade', description: '' },
    { id: 'tc-sales-wf', title: 'I freelance sales workflow', description: '' },
    { id: 'tc-aws-wf', title: 'I freelance AWS workflow', description: '' },
    { id: 'tc-bni', title: 'I freelance attended BNI', description: '' },
    { id: 'tc-blog-writing', title: 'I post articles personal blog x30 writing', description: '' },
    { id: 'tc-word-count', title: 'I do pkm Word Count', description: '' },
    { id: 'tc-kb-catalog', title: 'I do pkm KB catalog', description: '' },
    { id: 'tc-mandala', title: 'I do pkm mandala app', description: '' },
    { id: 'tc-gantt', title: 'I do pkm gantt chart app', description: '' },
    { id: 'tc-langchain', title: 'I do education teach LangChain', description: '' }
];

// Color palette for TypeB2
const colorPalette = ['#8931EF', '#F2CA19', '#FF00BD', '#0057E9', '#87E911', '#E11845'];

// Character preset for TypeB2
const charPreset = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';

// Export for use in app.js
const DATA = {
    typeA: typeAData,
    typeB: typeBData,
    typeB1: typeB1Data,
    typeB2: typeB2Data,
    typeC: typeCData,
    colorPalette,
    charPreset
};
